export const ALL_CELEBRITY_REQUEST = "ALL_CELEBRITY_REQUEST";
export const ALL_CELEBRITY_SUCCESS = "ALL_CELEBRITY_SUCCESS";
export const ALL_CELEBRITY_FAIL = "ALL_CELEBRITY_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
