export const DASHBOARD_INFO_REQUEST = "DASHBOARD_INFO_REQUEST";
export const DASHBOARD_INFO_SUCCESS = "DASHBOARD_INFO_SUCCESS";
export const DASHBOARD_INFO_FAIL = "DASHBOARD_INFO_FAIL";

export const DASHBOARD_SETTINGS_REQUEST = "DASHBOARD_SETTINGS_REQUEST";
export const DASHBOARD_SETTINGS_SUCCESS = "DASHBOARD_SETTINGS_SUCCESS";
export const DASHBOARD_SETTINGS_FAIL = "DASHBOARD_SETTINGS_FAIL";

export const SETTINGS_UPDATE_REQUEST = "SETTINGS_UPDATE_REQUEST";
export const SETTINGS_UPDATE_SUCCESS = "SETTINGS_UPDATE_SUCCESS";
export const SETTINGS_UPDATE_FAIL = "SETTINGS_UPDATE_FAIL";
