// ============================CELEBRITY CONSTANTS ============================

export const CELEBRITY_LIST_REQUEST = "CELEBRITY_LIST_REQUEST";
export const CELEBRITY_LIST_SUCCESS = "CELEBRITY_LIST_SUCCESS";
export const CELEBRITY_LIST_FAIL = "CELEBRITY_LIST_FAIL";

export const CELEBRITY_CREATE_REQUEST = "CELEBRITY_CREATE_REQUEST";
export const CELEBRITY_CREATE_SUCCESS = "CELEBRITY_CREATE_SUCCESS";
export const CELEBRITY_CREATE_FAIL = "CELEBRITY_CREATE_FAIL";

export const CELEBRITY_EDIT_REQUEST = "CELEBRITY_EDIT_REQUEST";
export const CELEBRITY_EDIT_SUCCESS = "CELEBRITY_EDIT_SUCCESS";
export const CELEBRITY_EDIT_FAIL = "CELEBRITY_EDIT_FAIL";

export const CELEBRITY_UPDATE_REQUEST = "CELEBRITY_UPDATE_REQUEST";
export const CELEBRITY_UPDATE_SUCCESS = "CELEBRITY_UPDATE_SUCCESS";
export const CELEBRITY_UPDATE_FAIL = "CELEBRITY_UPDATE_FAIL";

export const CELEBRITY_DELETE_REQUEST = "CELEBRITY_DELETE_REQUEST";
export const CELEBRITY_DELETE_SUCCESS = "CELEBRITY_DELETE_SUCCESS";
export const CELEBRITY_DELETE_FAIL = "CELEBRITY_DELETE_FAIL";
export const CELEBRITY_DELETE_RESET = "CELEBRITY_DELETE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
