// ============================CELEBRITY CONSTANTS ============================

export const CELEBRITY_LIST_REQUEST = "CELEBRITY_LIST_REQUEST";
export const CELEBRITY_LIST_SUCCESS = "CELEBRITY_LIST_SUCCESS";
export const CELEBRITY_LIST_FAIL = "CELEBRITY_LIST_FAIL";

export const CELEBRITY_CREATE_REQUEST = "CELEBRITY_CREATE_REQUEST";
export const CELEBRITY_CREATE_SUCCESS = "CELEBRITY_CREATE_SUCCESS";
export const CELEBRITY_CREATE_FAIL = "CELEBRITY_CREATE_FAIL";

export const CELEBRITY_DELETE_REQUEST = "CELEBRITY_DELETE_REQUEST";
export const CELEBRITY_DELETE_SUCCESS = "CELEBRITY_DELETE_SUCCESS";
export const CELEBRITY_DELETE_FAIL = "CELEBRITY_DELETE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
