// ============================MOVIES CONSTANTS ============================

export const MOVIE_LIST_REQUEST = "MOVIE_LIST_REQUEST";
export const MOVIE_LIST_SUCCESS = "MOVIE_LIST_SUCCESS";
export const MOVIE_LIST_FAIL = "MOVIE_LIST_FAIL";

export const MOVIE_CREATE_REQUEST = "MOVIE_CREATE_REQUEST";
export const MOVIE_CREATE_SUCCESS = "MOVIE_CREATE_SUCCESS";
export const MOVIE_CREATE_FAIL = "MOVIE_CREATE_FAIL";

export const MOVIE_EDIT_REQUEST = "MOVIE_EDIT_REQUEST";
export const MOVIE_EDIT_SUCCESS = "MOVIE_EDIT_SUCCESS";
export const MOVIE_EDIT_FAIL = "MOVIE_EDIT_FAIL";

export const MOVIE_UPDATE_REQUEST = "MOVIE_UPDATE_REQUEST";
export const MOVIE_UPDATE_SUCCESS = "MOVIE_UPDATE_SUCCESS";
export const MOVIE_UPDATE_FAIL = "MOVIE_UPDATE_FAIL";

export const MOVIE_DELETE_REQUEST = "MOVIE_DELETE_REQUEST";
export const MOVIE_DELETE_SUCCESS = "MOVIE_DELETE_SUCCESS";
export const MOVIE_DELETE_FAIL = "MOVIE_DELETE_FAIL";
export const MOVIE_DELETE_RESET = "MOVIE_DELETE_RESET";
